// action name
export const ADD_USER = 'ADD_USER'
export const SIGNOUT = 'SIGNOUT'
export const MODEL = 'HANDLE_AUTH_MODEL'
export const SIGNIN_USER = 'SIGNIN_USER'
export const CAR_DETAILS = 'CAR_DETAILS'
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'
export const UPDATE_LIKE = 'UPDATE_LIKE'
